name: Ant Media Server Release

on:
  push:
    branches: [ "add_helm_repo" ]
    paths-ignore:
      - '**/README.md'
      - '**/.github/**'
      - '**/package.sh'
      - '**/ams-k8s-ssl.sh'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write 

jobs:
  release:
      runs-on: ubuntu-latest  
      steps:
        - name: Checkout code
          uses: actions/checkout@v3
        - name: Get version
          id: version
          run: echo "version=$(cat VERSION)" >> $GITHUB_OUTPUT       
        - uses: "marvinpinto/action-automatic-releases@latest"
          with:
            repo_token: "${{ secrets.GITHUB_TOKEN }}"
            if: steps.version.outputs.released == 'true
            automatic_release_tag: ${{ steps.version.outputs.version }}
            prerelease: false
            files: |
              antmedia-${{ steps.version.outputs.version }}.tgz
